//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterSkypeParser.Lang {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BetterSkypeParser.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About Conversation.
        /// </summary>
        public static string AboutConversation {
            get {
                return ResourceManager.GetString("AboutConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The account is linked to.
        /// </summary>
        public static string AccountLinkedTo {
            get {
                return ResourceManager.GetString("AccountLinkedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на have added.
        /// </summary>
        public static string AddMemberPlural {
            get {
                return ResourceManager.GetString("AddMemberPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на has added.
        /// </summary>
        public static string AddMemberSingular {
            get {
                return ResourceManager.GetString("AddMemberSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на admin.
        /// </summary>
        public static string AdminRole {
            get {
                return ResourceManager.GetString("AdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Audio Message.
        /// </summary>
        public static string AudioMessage {
            get {
                return ResourceManager.GetString("AudioMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на bit(s).
        /// </summary>
        public static string Bits {
            get {
                return ResourceManager.GetString("Bits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на byte(s).
        /// </summary>
        public static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Call ended.
        /// </summary>
        public static string CallEnded {
            get {
                return ResourceManager.GetString("CallEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Call started.
        /// </summary>
        public static string CallStarted {
            get {
                return ResourceManager.GetString("CallStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cast.
        /// </summary>
        public static string Cast {
            get {
                return ResourceManager.GetString("Cast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на cast.
        /// </summary>
        public static string CastAccusative {
            get {
                return ResourceManager.GetString("CastAccusative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на cast.
        /// </summary>
        public static string CastDative {
            get {
                return ResourceManager.GetString("CastDative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Request to add to contacts.
        /// </summary>
        public static string ContactRequest {
            get {
                return ResourceManager.GetString("ContactRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Conversations: {0}.
        /// </summary>
        public static string ConversationsCountFormat {
            get {
                return ResourceManager.GetString("ConversationsCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (del.).
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на have deleted.
        /// </summary>
        public static string DeleteMemberPlural {
            get {
                return ResourceManager.GetString("DeleteMemberPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на has deleted.
        /// </summary>
        public static string DeleteMemberSingular {
            get {
                return ResourceManager.GetString("DeleteMemberSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на have left the.
        /// </summary>
        public static string DeleteYourselfPlural {
            get {
                return ResourceManager.GetString("DeleteYourselfPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на has left the.
        /// </summary>
        public static string DeleteYourselfSingular {
            get {
                return ResourceManager.GetString("DeleteYourselfSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (edit.).
        /// </summary>
        public static string Edited {
            get {
                return ResourceManager.GetString("Edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Emoticon.
        /// </summary>
        public static string Emoticon {
            get {
                return ResourceManager.GetString("Emoticon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export Time: {0}.
        /// </summary>
        public static string ExportTimeFormat {
            get {
                return ResourceManager.GetString("ExportTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extras.
        /// </summary>
        public static string Extras {
            get {
                return ResourceManager.GetString("Extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file type is unknown.
        /// </summary>
        public static string FileTypeUnknown {
            get {
                return ResourceManager.GetString("FileTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The image is not loaded, check your internet connection.
        /// </summary>
        public static string GIFNotLoaded {
            get {
                return ResourceManager.GetString("GIFNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GB.
        /// </summary>
        public static string Gigabytes {
            get {
                return ResourceManager.GetString("Gigabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to contact.
        /// </summary>
        public static string GoToContact {
            get {
                return ResourceManager.GetString("GoToContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на guest account.
        /// </summary>
        public static string GuestAccount {
            get {
                return ResourceManager.GetString("GuestAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на have disclosed.
        /// </summary>
        public static string HistoryDisclosedPlural {
            get {
                return ResourceManager.GetString("HistoryDisclosedPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на has disclosed.
        /// </summary>
        public static string HistoryDisclosedSingular {
            get {
                return ResourceManager.GetString("HistoryDisclosedSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на have hidden.
        /// </summary>
        public static string HistoryHiddenPlural {
            get {
                return ResourceManager.GetString("HistoryHiddenPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на has hidden.
        /// </summary>
        public static string HistoryHiddenSingular {
            get {
                return ResourceManager.GetString("HistoryHiddenSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на joining the.
        /// </summary>
        public static string Joining {
            get {
                return ResourceManager.GetString("Joining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на have banned.
        /// </summary>
        public static string JoiningDisabledPlural {
            get {
                return ResourceManager.GetString("JoiningDisabledPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на has banned.
        /// </summary>
        public static string JoiningDisabledSingular {
            get {
                return ResourceManager.GetString("JoiningDisabledSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на have allowed.
        /// </summary>
        public static string JoiningEnabledPlural {
            get {
                return ResourceManager.GetString("JoiningEnabledPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на has allowed.
        /// </summary>
        public static string JoiningEnabledSingular {
            get {
                return ResourceManager.GetString("JoiningEnabledSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на JSON File.
        /// </summary>
        public static string JSONFile {
            get {
                return ResourceManager.GetString("JSONFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KB.
        /// </summary>
        public static string Kilobytes {
            get {
                return ResourceManager.GetString("Kilobytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MB.
        /// </summary>
        public static string Megabytes {
            get {
                return ResourceManager.GetString("Megabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на member.
        /// </summary>
        public static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на members.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Members: {0}.
        /// </summary>
        public static string MembersCountFormat {
            get {
                return ResourceManager.GetString("MembersCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на the message history.
        /// </summary>
        public static string MessageHistory {
            get {
                return ResourceManager.GetString("MessageHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Messages: {0}.
        /// </summary>
        public static string MessagesCountFormat {
            get {
                return ResourceManager.GetString("MessagesCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The message type is unknown.
        /// </summary>
        public static string MessageTypeUnknown {
            get {
                return ResourceManager.GetString("MessageTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Missed call.
        /// </summary>
        public static string MissedCall {
            get {
                return ResourceManager.GetString("MissedCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Moji.
        /// </summary>
        public static string Moji {
            get {
                return ResourceManager.GetString("Moji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No Image Available.
        /// </summary>
        public static string NoImageAvailable {
            get {
                return ResourceManager.GetString("NoImageAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open File.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на the {0} role for.
        /// </summary>
        public static string RoleUpdateFormat {
            get {
                return ResourceManager.GetString("RoleUpdateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на have set.
        /// </summary>
        public static string RoleUpdatePlural {
            get {
                return ResourceManager.GetString("RoleUpdatePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на has set.
        /// </summary>
        public static string RoleUpdateSingular {
            get {
                return ResourceManager.GetString("RoleUpdateSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sent contact.
        /// </summary>
        public static string SentContact {
            get {
                return ResourceManager.GetString("SentContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (system account).
        /// </summary>
        public static string SystemAccount {
            get {
                return ResourceManager.GetString("SystemAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TB.
        /// </summary>
        public static string Terabytes {
            get {
                return ResourceManager.GetString("Terabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thread.
        /// </summary>
        public static string Thread {
            get {
                return ResourceManager.GetString("Thread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на thread.
        /// </summary>
        public static string ThreadAccusative {
            get {
                return ResourceManager.GetString("ThreadAccusative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на thread.
        /// </summary>
        public static string ThreadDative {
            get {
                return ResourceManager.GetString("ThreadDative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на the name to.
        /// </summary>
        public static string TopicUpdateNameTo {
            get {
                return ResourceManager.GetString("TopicUpdateNameTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на have changed.
        /// </summary>
        public static string TopicUpdatePlural {
            get {
                return ResourceManager.GetString("TopicUpdatePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на has changed.
        /// </summary>
        public static string TopicUpdateSingular {
            get {
                return ResourceManager.GetString("TopicUpdateSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown GIF file.
        /// </summary>
        public static string UnknownGIFFile {
            get {
                return ResourceManager.GetString("UnknownGIFFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на user.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You.
        /// </summary>
        public static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your ID: {0}.
        /// </summary>
        public static string YourIDFormat {
            get {
                return ResourceManager.GetString("YourIDFormat", resourceCulture);
            }
        }
    }
}
